use_frameworks!

platform :ios, '8.0'

target 'PYBaseView_Example' do
  pod 'PYBaseView', :path => '../'

  target 'PYBaseView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
