use_frameworks!

platform :ios, '8.0'

target 'PYBaseViews_Example' do
  pod 'PYBaseViews', :path => '../'
pod 'PYBaseEventHandler'
  target 'PYBaseViews_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
